spring:
    datasource:
        password: root
        url: jdbc:postgresql://localhost:5432/keeppo
        username: root
    jpa:
        hibernate:
            ddl-auto: update
            show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

server:
    port : 7777
    servlet:
        context-path: /api/v1/
