spring:
  profiles:
    active:
    - dev

---
# local dev

spring:
    profiles: dev

    datasource:
        password: root
        url: jdbc:postgresql://localhost:5432/keeppo
        username: root
    jpa:
        hibernate:
            ddl-auto: update # COMMENT THIS IN PRODUCTION
            show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
server:
    port : 7777
    servlet:
        context-path: /api/v1/
    ssl: # mkcert -pkcs12 localhost => DEV ONLY self signed 
        key-store: classpath:localhost.p12
        key-store-password: changeit # for dev purpose, we don't care
        key-store-type: pkcs12
---
# change active profil to - test for testing 
# Not required to change, since ActiveProfil in test annotation is test and h2 is scoped for this profil test

spring:
    profiles: test

    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:testdb;
        username: sa
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
